### ISSUE TITLE
Epic: Project setup

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/code-tube#1]
# Project setup

Feature: Project setup with all dependencies 

## Epic Description

This Feature will add deps, requirements and code structure for the video library app

## List of Tasks (Complete in order)

- [ ] 1. Add basic folder structure
- [ ] 2. Add required deps
- [ ] 3. Complete routing setup
- [ ] 4. Add mockbee setup
