### ISSUE TITLE
Epic: Playlist management

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/code-tube#11]
# Epic: Playlist management

Feature: Playlist management

## Epic Description

This Feature will add the playlist management feature in-app

## List of Tasks (Complete in order)

1. [ ] Add playlist context
2. [ ] Add reducer cases for playlist
3. [ ] Create services for playlist management
4. [ ] Create a component for showing playlists
5. [ ] Create a modal for adding videos to the playlist
6. [ ] Create a page for showing all playlists
