### ISSUE TITLE
Epic: Video listing page

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/code-tube#2]
# Video listing page

Feature: Video listing

## Epic Description

This Feature will 

## List of Tasks (Complete in order)

- [ ] 1. Show all available videoes
- [ ] 2. Add videos context
- [ ] 3. Add video categories
- [ ] 4. Create single video card
- [ ] 5. Show filtered videos by categories
