### ISSUE TITLE
Epic: Home page 

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/code-tube#4]
# Epic Title

Feature: Home page

## Epic Description

This Feature will complete the home page

## List of Tasks (Complete in order)

1. [ ] Create categories context
2. [ ] Add categories context
3. [ ] Add categories chips container
4. [ ] Add categories filter
