### ISSUE TITLE
Epic: History management

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/code-tube#9]
# History Management

Feature: Awesome Feature Title

## Epic Description

This Feature will add a history management in app

## List of Tasks (Complete in order)

1. [ ] Create history context
2. [ ] Add dispatch for fetching videos, adding videos and removing videos in history
3. [ ] Add APIs for the above dispatch
4. [ ] Add a history page in UI for showing all watched videos
5. [ ] Add a clear history button and functionality
